### Criar Bairro
POST http://localhost:8080/bairros
Content-Type: application/json

{
  "nome": "Serra Pelada"
}

###

### Listar Bairros
GET http://localhost:8080/bairros

###

### Buscar Bairro por ID
GET http://localhost:8080/bairros/1

###

### Atualizar Bairro
PUT http://localhost:8080/bairros/2
Content-Type: application/json

{
  "nome": "Manoel Santana"
}

###

### Deletar Bairro
DELETE http://localhost:8080/bairros/3
#########################################################################################################

### Criar Endereco
POST http://localhost:8080/enderecos
Content-Type: application/json

{
  "rua": "Rua Beira Rio",
  "numero": "354",
  "complemento": "UBS",
  "cep": "39935-000",
  "cidade": "Santo Antônio do Jacinto",
  "idBairro": 1
}

###

### Listar Enderecos
GET http://localhost:8080/enderecos

###

### Buscar Endereco
GET http://localhost:8080/enderecos/1

###

### Atualizar Endereco
PUT http://localhost:8080/enderecos/1
Content-Type: application/json

{
  "rua": "Rua Treze de Janeiro",
  "numero": "702",
  "complemento": "Casa",
  "cep": "39935-000",
  "cidade": "Santo Antônio do Jacinto",
  "idBairro": 1
}

###

### Deletar Endereco
DELETE http://localhost:8080/enderecos/2
#########################################################################################################

### Criar Paciente
POST http://localhost:8080/pacientes
Content-Type: application/json

{
  "nome": "Maria Fernanda Ferraz Brito de Oliveira",
  "cpf": "00011100045",
  "dataNascimento": "2019-04-17",
  "sexo": "FEMININO",
  "telefone": "(33) 98843-5416",
  "idEndereco": 1
}

###

### Listar Pacientes
GET http://localhost:8080/pacientes

###

### Buscar Paciente
GET http://localhost:8080/pacientes/1

###

### Atualizar Paciente
PUT http://localhost:8080/pacientes/2
Content-Type: application/json

{
  "nome": "Gleiziane Ferraz Aguiar Lima",
  "cpf": "12345678901",
  "dataNascimento": "1982-04-15",
  "sexo": "FEMININO",
  "telefone": "(33) 98858-2439",
  "idEndereco": 1
}

###

### Deletar Paciente
DELETE http://localhost:8080/pacientes/1
#########################################################################################################
### Criar Doenca
POST http://localhost:8080/doencas
Content-Type: application/json

{
  "nome": "Diabetes Mellitus",
  "tipo": "CRONICA",
  "classificacao": "Metabólica"
}
###

### Listar Doenças
GET http://localhost:8080/doencas

###

### Buscar Doença
GET http://localhost:8080/doencas/3

###

### Atualizar Doença
PUT http://localhost:8080/doencas/1
Content-Type: application/json

{
  "nome": "Dengue",
  "tipo": "TRANSMISSIVEL",
  "classificacao": "Viral"
}

###

### Deletar Doença
DELETE http://localhost:8080/doencas/3
#########################################################################################################

### Criar Unidade de Saúde
POST http://localhost:8080/unidades
Content-Type: application/json

{
  "nome": "UBS ESF Saúde Para Todos",
  "telefone": "(33) 3424-1544",
  "enderecoId": 4
}

###

### Listar Unidades de Saúde
GET http://localhost:8080/unidades

###

### Buscar Unidade
GET http://localhost:8080/unidades/1

###

### Atualizar Unidade
PUT http://localhost:8080/unidades/1
Content-Type: application/json

{
  "nome": "UBS Dona Carmita Freitas dos Santos",
  "telefone": "(33) 3424-1534",
  "enderecoId": 3
}

###

### Deletar Unidade
DELETE http://localhost:8080/unidades/2
#########################################################################################################

### Criar Médico
POST http://localhost:8080/medicos
Content-Type: application/json

{
  "nome": "Yure Brito",
  "crm": "123456",
  "especialidade": "Clínico Geral",
  "unidadeId": 1
}
###

### Listar Médicos
GET http://localhost:8080/medicos

###

### Buscar Médico
GET http://localhost:8080/medicos/2

###

### Atualizar Médico
PUT http://localhost:8080/medicos/2
Content-Type: application/json

{
  "nome": "Yure Brito",
  "crm": "654321",
  "especialidade": "Clínico Geral",
  "unidadeId": 1
}

###

### Deletar Médico
DELETE http://localhost:8080/medicos/1

##########################################################################################################

### Criar Consulta
POST http://localhost:8080/consultas
Content-Type: application/json

{
  "dataConsulta": "2025-07-19T11:00:00",
  "observacoes": "Paciente apresentou sintomas de dor de cabeça.",
  "pacienteId": 2,
  "unidadeId": 1,
  "medicoId": 2,
  "doencaId": 4
}

###

### Listar Consultas
GET http://localhost:8080/consultas

### Buscar Consulta
GET http://localhost:8080/consultas/2

### Atualizar Consulta
PUT http://localhost:8080/consultas/2
Content-Type: application/json

{
  "dataConsulta": "2026-02-24T11:30:00",
  "observacoes": "Paciente apresentou sintomas de febre, dor de cabeça.",
  "pacienteId": 2,
  "unidadeId": 1,
  "medicoId": 2,
  "doencaId": 2
}

###

### Deletar Consulta
DELETE http://localhost:8080/consultas/2
###########################################################################################################

### Criar Perfil
POST http://localhost:8080/perfis
Content-Type: application/json

{
  "nome": "Outro"
}

###

### Listar Perfis
GET http://localhost:8080/perfis

###

### Buscar Perfil
GET http://localhost:8080/perfis/1
###

### Atualizar Perfil
PUT http://localhost:8080/perfis/3
Content-Type: application/json

{
  "nome": "Médico"
}
###

### Deletar Perfil
DELETE http://localhost:8080/perfis/3
###########################################################################################################

### Criar Usuário
POST http://localhost:8080/usuarios
Content-Type: application/json

{
  "nome": "Usuário Teste",
  "email": "teste@teste.com",
  "senha": "teste4444",
  "perfilId": 1
}

###

### Listar Usuários
GET http://localhost:8080/usuarios

###

### Buscar Usuário
GET http://localhost:8080/usuarios/3
###

### Atualizar Usuário
PUT http://localhost:8080/usuarios/3
Content-Type: application/json

{
  "nome": "Emanuelle Ferraz",
  "email": "emanuelle.ferraz@aluno.ufop.edu.br",
  "senha": "teste123456",
  "perfilId": 1
}

###

### Deletar Usuário
DELETE http://localhost:8080/usuarios/4

############################################################################################################

### Criar Agente

POST http://localhost:8080/agentes
Content-Type: application/json

{
  "nome": "Sirleide Gomes da Silva",
  "telefone": "(33) 98965-9173",
  "unidadeId": 3,
  "bairroId": 2
}

###

### Listar Agentes
GET http://localhost:8080/agentes

###

### Buscar Agente
GET http://localhost:8080/agentes/1
###

### Atualizar Agente
PUT http://localhost:8080/agentes/1
Content-Type: application/json

{
  "nome": "Maria Rosa Soares",
  "telefone": "(33) 98765-5876",
  "unidadeId": 1,
  "bairroId": 1
}
###

### Deletar Agente
DELETE http://localhost:8080/agentes/2
############################################################################################################

### Cria Visita
POST http://localhost:8080/visitas
Content-Type: application/json

{
  "dataVisita": "2026-02-01T14:00:00",
  "observacoes": "Paciente com saúde em dia.",
  "agenteId": 1,
  "pacienteId": 2
}

###

### Listar Visitas
GET http://localhost:8080/visitas
###

### Buscar Visita
GET http://localhost:8080/visitas/1
###

### Atualizar Visita
PUT http://localhost:8080/visitas/1
Content-Type: application/json

{
  "dataVisita": "2026-03-02T14:30:00",
  "observacoes": "Paciente apresentou sintomas de febre e dor de cabeça.",
  "agenteId": 1,
  "pacienteId": 2
}

###

### Deletar Visita
DELETE http://localhost:8080/visitas/2
#############################################################################################################

### Criar Vacina
POST http://localhost:8080/vacinas
Content-Type: application/json

  {
    "nome": "Febre Amarela",
    "fabricante": "Bio-Manguinhos/Fiocruz",
    "dosagem": "Dose única"
  }

###

### Listar Vacinas
GET http://localhost:8080/vacinas
###

### Buscar Vacina
GET http://localhost:8080/vacinas/1
###

### Atualizar Vacina
PUT http://localhost:8080/vacinas/3
Content-Type: application/json

{
  "nome": "Febre Amarela",
  "fabricante": "Fiocruz",
  "dosagem": "Dose única"
}
###

### Deletar Vacina
DELETE http://localhost:8080/vacinas/3
#############################################################################################################

### Criar Profissional Enfermagem
POST http://localhost:8080/enfermeiros
Content-Type: application/json

{
  "nome": "Liriamar Oliveira",
  "coren": "123686",
  "telefone": "(33) 98785-6321",
  "unidadeId": 1,
  "tipo": "Enfermeiro"
}

###

### Listar Profissionais de Enfermagem
GET http://localhost:8080/enfermeiros
###

### Buscar Profissional de Enfermagem
GET http://localhost:8080/enfermeiros/1
###

### Atualizar Profissional de Enfermagem
PUT http://localhost:8080/enfermeiros/1
Content-Type: application/json

{
  "nome": "Maria Aparecida Silva",
  "coren": "153356",
  "telefone": "(33) 98765-4321",
  "unidadeId": 1,
  "tipo": "Enfermeiro"
}

###

### Deletar Profissional de Enfermagem
DELETE http://localhost:8080/enfermeiros/2
##############################################################################################################

### Criar Aplicação de Vacina
POST http://localhost:8080/aplicacoes-vacina
Content-Type: application/json

{
  "dataAplicacao": "2024-12-01T10:00:00",
  "dose": "Dose anual",
  "pacienteId": 2,
  "vacinaId": 1,
  "enfermeiroId": 1
}

###

### Listar Aplicações de Vacina
GET http://localhost:8080/aplicacoes-vacina
###

### Buscar Aplicação de Vacina
GET http://localhost:8080/aplicacoes-vacina/1
###

### Atualizar Aplicação de Vacina
PUT http://localhost:8080/aplicacoes-vacina/2
Content-Type: application/json

{
  "dataAplicacao": "2025-11-01T10:00:00",
  "dose": "Dose anual",
  "pacienteId": 2,
  "vacinaId": 1,
  "enfermeiroId": 1
}
###

### Deletar Aplicação de Vacina
DELETE http://localhost:8080/aplicacoes-vacina/2
###############################################################################################################

### Visualizar Resumo
GET http://localhost:8080/pacientes/2/resumo
###